name: FE
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  intl: ^0.18.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_assets: ^0.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/main/
    - assets/shop/
    - assets/theme/
    - assets/images/
  
  fonts:
    - family: SUITE
      fonts:
        - asset: assets/font/SUITE/SUITE-Bold.otf
          weight: 600
        - asset: assets/font/SUITE/SUITE-Regular.otf
          weight: 400 

